version: '3.8'

services:
  geojson-converter:
    build: .
    container_name: geojson-geobuf-converter
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - geojson-network

  # Development service (optional)
  geojson-converter-dev:
    build: .
    container_name: geojson-geobuf-converter-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    profiles:
      - dev
    networks:
      - geojson-network

networks:
  geojson-network:
    driver: bridge 