name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's New
          
          This release includes the following changes:
          
          - Bug fixes and improvements
          - Performance enhancements
          - Documentation updates
          
          ## Installation
          
          ```bash
          npm install geojson-geobuf-converter@${{ github.ref_name }}
          ```
          
          ## Docker
          
          ```bash
          docker pull openapphub/geojson-geobuf-converter:${{ github.ref_name }}
          ```
          
          ## Changelog
          
          See the [full changelog](https://github.com/openapphub/geojson-geobuf-converter/compare/v${{ github.ref_name }}...main) for detailed changes.
        draft: false
        prerelease: false 